/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oopjava;

import java.awt.Component;
import javax.swing.UnsupportedLookAndFeelException;
 import java.awt.TextField ; 
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javaapplication1withant.SubClass_Child;
 import javax.swing.JTextField ;
import javax.swing.UIManager ;  
import javax.swing.UIManager.LookAndFeelInfo ;   
/**
 *
 * @author NJL
 */
public class oopjava extends javax.swing.JFrame {

    /**
     * Creates new form oopjava
     */
    public oopjava() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArearec = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        jtextSubtotal = new javax.swing.JTextField();
        jTotal = new javax.swing.JTextField();
        jTax = new javax.swing.JTextField();
        jLTax = new javax.swing.JLabel();
        jLsubtax = new javax.swing.JLabel();
        jLTotal = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jtexttotalitems = new javax.swing.JTextField();
        jLTotal8 = new javax.swing.JLabel();
        jtextdrink = new javax.swing.JTextField();
        jLsubtax4 = new javax.swing.JLabel();
        jtxtmeal = new javax.swing.JTextField();
        jLTax6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLTax1 = new javax.swing.JLabel();
        jLsubtax1 = new javax.swing.JLabel();
        jLTotal1 = new javax.swing.JLabel();
        baconannchese = new javax.swing.JTextField();
        jtextFiletoffish = new javax.swing.JTextField();
        jLTax3 = new javax.swing.JLabel();
        jchikenlegend = new javax.swing.JTextField();
        jLTotal3 = new javax.swing.JLabel();
        jLTotal4 = new javax.swing.JLabel();
        jchikenburgermeal = new javax.swing.JTextField();
        jLsubtax2 = new javax.swing.JLabel();
        jchikenburger = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLTax4 = new javax.swing.JLabel();
        jLsubtax3 = new javax.swing.JLabel();
        jLTotal5 = new javax.swing.JLabel();
        jtextchocomilkShake = new javax.swing.JTextField();
        jtextvanilliacone = new javax.swing.JTextField();
        jtxtMilkShake = new javax.swing.JTextField();
        jLTax5 = new javax.swing.JLabel();
        jLTotal6 = new javax.swing.JLabel();
        jtxtclassvan = new javax.swing.JTextField();
        jLTotal7 = new javax.swing.JLabel();
        jtxtvanMilkShake = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jBtnReset = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 10));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 58)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Restaurant Management System ");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 8));
        jLabel1.setPreferredSize(new java.awt.Dimension(176, 16));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jTextArearec.setColumns(20);
        jTextArearec.setRows(5);
        jScrollPane1.setViewportView(jTextArearec);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jtextSubtotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtextSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextSubtotalActionPerformed(evt);
            }
        });

        jTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTotalActionPerformed(evt);
            }
        });

        jTax.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTaxActionPerformed(evt);
            }
        });

        jLTax.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLTax.setText("Tax         ");

        jLsubtax.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLsubtax.setText("SubTotal  ");

        jLTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLTotal.setText("Total      ");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTax, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLsubtax, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtextSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTax, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtextSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLsubtax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLTotal)
                    .addComponent(jTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jtexttotalitems.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtexttotalitems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtexttotalitemsActionPerformed(evt);
            }
        });

        jLTotal8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLTotal8.setText("Total Cost of Items");

        jtextdrink.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtextdrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextdrinkActionPerformed(evt);
            }
        });

        jLsubtax4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLsubtax4.setText("Cost of Drinks ");

        jtxtmeal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtxtmeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtmealActionPerformed(evt);
            }
        });

        jLTax6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLTax6.setText("Cost of Meal");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLTax6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLsubtax4)
                    .addComponent(jLTotal8, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtextdrink, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtmeal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtexttotalitems, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtmeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTax6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtextdrink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLsubtax4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtexttotalitems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTotal8))
                .addGap(18, 18, 18))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jLTax1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLTax1.setText("Meals");

        jLsubtax1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLsubtax1.setText("Fielt-O-Fish");

        jLTotal1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLTotal1.setText("Chiken Legend");

        baconannchese.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        baconannchese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baconanncheseActionPerformed(evt);
            }
        });

        jtextFiletoffish.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtextFiletoffish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextFiletoffishActionPerformed(evt);
            }
        });

        jLTax3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jchikenlegend.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jchikenlegend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchikenlegendActionPerformed(evt);
            }
        });

        jLTotal3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLTotal3.setText("Chiken Burger Meal");

        jLTotal4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLTotal4.setText("Bacon and cheese burger");

        jchikenburgermeal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jchikenburgermeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchikenburgermealActionPerformed(evt);
            }
        });

        jLsubtax2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLsubtax2.setText("Chiken Burger");

        jchikenburger.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jchikenburger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchikenburgerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLTotal1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTotal3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTotal4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtextFiletoffish, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jchikenlegend, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jchikenburgermeal, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(baconannchese, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jchikenburger, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(178, 178, 178)
                                .addComponent(jLTax3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLsubtax1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLsubtax2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLTax1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTax1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLTax3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtextFiletoffish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLsubtax1))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jchikenburger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLsubtax2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jchikenlegend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTotal1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jchikenburgermeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTotal3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(baconannchese, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTotal4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jLTax4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLTax4.setText("Drinks");

        jLsubtax3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLsubtax3.setText("Vanilla cone");

        jLTotal5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLTotal5.setText("Classic vanilla");

        jtextchocomilkShake.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtextchocomilkShake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextchocomilkShakeActionPerformed(evt);
            }
        });

        jtextvanilliacone.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtextvanilliacone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextvanilliaconeActionPerformed(evt);
            }
        });

        jtxtMilkShake.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtxtMilkShake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtMilkShakeActionPerformed(evt);
            }
        });

        jLTax5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLTax5.setText("Milk shake");

        jLTotal6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLTotal6.setText("Vanilla Milk Shake");

        jtxtclassvan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtxtclassvan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtclassvanActionPerformed(evt);
            }
        });

        jLTotal7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLTotal7.setText("Chocolate Milk Shake");

        jtxtvanMilkShake.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtxtvanMilkShake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtvanMilkShakeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLsubtax3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTax5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTotal5, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTotal6, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTotal7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtMilkShake, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtextvanilliacone, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtclassvan, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtvanMilkShake, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtextchocomilkShake, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLTax4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTax4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtMilkShake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTax5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtextvanilliacone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLsubtax3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTotal5)
                    .addComponent(jtxtclassvan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTotal6)
                    .addComponent(jtxtvanMilkShake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTotal7)
                    .addComponent(jtextchocomilkShake, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Total");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jBtnReset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBtnReset.setText("Reset");
        jBtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnResetActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Receipt");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jButton4)
                .addGap(46, 46, 46)
                .addComponent(jBtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnReset)
                    .addComponent(jButton3)
                    .addComponent(jButton1)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtexttotalitemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtexttotalitemsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtexttotalitemsActionPerformed

    private void jtextdrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextdrinkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextdrinkActionPerformed

    private void jtxtmealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtmealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtmealActionPerformed

    private void baconanncheseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baconanncheseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_baconanncheseActionPerformed

    private void jtextFiletoffishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextFiletoffishActionPerformed
        // TODO 
    }//GEN-LAST:event_jtextFiletoffishActionPerformed

    private void jchikenlegendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchikenlegendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jchikenlegendActionPerformed

    private void jchikenburgermealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchikenburgermealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jchikenburgermealActionPerformed

    private void jtextchocomilkShakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextchocomilkShakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextchocomilkShakeActionPerformed

    private void jtextvanilliaconeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextvanilliaconeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextvanilliaconeActionPerformed

    private void jtxtMilkShakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtMilkShakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtMilkShakeActionPerformed

    private void jtxtclassvanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtclassvanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtclassvanActionPerformed

    private void jtxtvanMilkShakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtvanMilkShakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtvanMilkShakeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       // TODO add your handling code here: 
       SubClass_Child  iExit = new SubClass_Child () ;  
       
       iExit.iExitSystem();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTaxActionPerformed

    private void jTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTotalActionPerformed

    private void jtextSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextSubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextSubtotalActionPerformed

    private void jBtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnResetActionPerformed
   
        JTextField cleartext = null ;  
        
        for (Component c:jPanel9.getComponents()){  
            if(c.getClass().toString().contains("javax.swing.JTextField")){ 
                cleartext = (JTextField)c;  
                cleartext.setText("0") ; 
            }
        }

        
        //============================================nextpanel=========== 
        
        
         for (Component c:jPanel8.getComponents()){  
            if(c.getClass().toString().contains("javax.swing.JTextField")){ 
                cleartext = (JTextField)c;  
                cleartext.setText(null) ; 
            }
        } 
         
          for (Component c:jPanel9.getComponents()){  
            if(c.getClass().toString().contains("javax.swing.JTextField")){ 
                cleartext = (JTextField)c;  
                cleartext.setText(null) ; 
            }
        }
           for (Component c:jPanel11.getComponents()){  
            if(c.getClass().toString().contains("javax.swing.JTextField")){ 
                cleartext = (JTextField)c;  
                cleartext.setText("0") ; 
            }
        }
           
         
          for (Component c:jPanel5.getComponents()){  
            if(c.getClass().toString().contains("javax.swing.JTextField")){ 
                cleartext = (JTextField)c;  
                cleartext.setText(null) ; 
            }
        }
         jTextArearec.setText(null);
    }//GEN-LAST:event_jBtnResetActionPerformed

    private void jchikenburgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchikenburgerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jchikenburgerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
              double iTax , iSubTotal , Itotal ; 
         SubClass_Child Itemcost = new SubClass_Child() ;  
         Itemcost.Filet_o_fish= Itemcost.pFilet_o_fish * Double.parseDouble(jtextFiletoffish.getText()) ;  
         Itemcost.chikenburger= Itemcost.pchikenburger * Double.parseDouble(jchikenburger.getText()) ;    
         Itemcost.ChikenLengend= Itemcost.pChikenLengend * Double.parseDouble(jchikenlegend.getText()) ;
         Itemcost.chikenburgerM= Itemcost.pchikenburgerM * Double.parseDouble(jchikenburgermeal.getText()) ;
         Itemcost.BaconCheeseBurger= Itemcost.pBaconCheeseBurger * Double.parseDouble(baconannchese.getText()) ;
     
          
          
         Itemcost.MilkShake= Itemcost.pMilkShake * Double.parseDouble(jtxtMilkShake.getText()) ;  
         Itemcost.VanMilkShake= Itemcost.pVanMilkShake * Double.parseDouble(jtextvanilliacone.getText()) ;    
         Itemcost.VanillaCone= Itemcost.pVanillaCone * Double.parseDouble(jtxtclassvan.getText()) ;
         Itemcost.ClassVanilla= Itemcost.pClassVanilla * Double.parseDouble(jtxtvanMilkShake.getText()) ;
         Itemcost.ChocoMilk= Itemcost.pChocoMilk * Double.parseDouble(jtextchocomilkShake.getText()) ; 
         
         
        iSubTotal = Itemcost.GetAmount() ; 
        iTax = Itemcost.cFindTax(iSubTotal); 
        Itotal = iSubTotal + iTax ; 
        
        String subTotal =String.format("£%.2f", iSubTotal) ;
        jtextSubtotal.setText(subTotal);  
        
        // ----------------------------------
        
       
        
          String Tax =String.format("£%.2f", iTax) ;
          jTax.setText(Tax); 
        
          String Total  =String.format("£%.2f", Itotal) ;
        jTotal.setText(Total);  
        
        String Meal = String.format("£%.2f",Itemcost.Meals) ;
        jtxtmeal.setText(Meal); 
        
        String Drink = String.format("£%.2f",Itemcost.Drinks) ;
        jtextdrink.setText(Drink); 
        
         String costtotalitems = String.format("£%.2f",Itemcost.TotalofMD) ;
        jtexttotalitems.setText(costtotalitems); 
        //
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
 
           int refs  = 1325 + (int) (Math.random()*4238) ; 
           
           Calendar timer = Calendar.getInstance() ; 
           timer.getTime(); 
           SimpleDateFormat tTime  =  new  SimpleDateFormat("HH:mm:ss");  
           tTime.format(timer.getTime()) ; 
           
           SimpleDateFormat Tdate  =  new  SimpleDateFormat("dd:mm:yyyy");  
           Tdate.format(timer.getTime()) ; 
           
          
            jTextArearec.append("\t Restaurant Management System :  \n "
                             + "\n =================================\n"
                               + "Meals: \t\t  " + jtxtmeal.getText() + "\n\n"
                      + " Drinks:\t\t " + jtextdrink.getText() + "\n\n"
                       + " Costs of Items:\t\t " + jtexttotalitems.getText() + "\n\n "
                        + "================================="+ "\n\n" + 
                        "Tax : \t\t" + jTax.getText() + "\n\n" + 
                    "SubTotal : \t\t " + jtextSubtotal.getText() + "\n\n" 
                     + "Total : \t\t " + jTotal.getText() + "\n" + 
                    "=================================" + 
                    
                    "\nDate  : " + Tdate.format(timer.getTime()) + "\tTime : " + 
                    tTime.format(timer.getTime()) + 
                    "\n\n\t\tThank you for comming  "
                        ); 
       
           
           
           
        
          // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.lang.ClassNotFoundException
     * @throws java.lang.InstantiationException
     * @throws java.lang.IllegalAccessException
     * @throws javax.swing.UnsupportedLookAndFeelException
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(oopjava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(oopjava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(oopjava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(oopjava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new oopjava().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField baconannchese;
    private javax.swing.JButton jBtnReset;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLTax;
    private javax.swing.JLabel jLTax1;
    private javax.swing.JLabel jLTax3;
    private javax.swing.JLabel jLTax4;
    private javax.swing.JLabel jLTax5;
    private javax.swing.JLabel jLTax6;
    private javax.swing.JLabel jLTotal;
    private javax.swing.JLabel jLTotal1;
    private javax.swing.JLabel jLTotal3;
    private javax.swing.JLabel jLTotal4;
    private javax.swing.JLabel jLTotal5;
    private javax.swing.JLabel jLTotal6;
    private javax.swing.JLabel jLTotal7;
    private javax.swing.JLabel jLTotal8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLsubtax;
    private javax.swing.JLabel jLsubtax1;
    private javax.swing.JLabel jLsubtax2;
    private javax.swing.JLabel jLsubtax3;
    private javax.swing.JLabel jLsubtax4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTax;
    private javax.swing.JTextArea jTextArearec;
    private javax.swing.JTextField jTotal;
    private javax.swing.JTextField jchikenburger;
    private javax.swing.JTextField jchikenburgermeal;
    private javax.swing.JTextField jchikenlegend;
    private javax.swing.JTextField jtextFiletoffish;
    private javax.swing.JTextField jtextSubtotal;
    private javax.swing.JTextField jtextchocomilkShake;
    private javax.swing.JTextField jtextdrink;
    private javax.swing.JTextField jtexttotalitems;
    private javax.swing.JTextField jtextvanilliacone;
    private javax.swing.JTextField jtxtMilkShake;
    private javax.swing.JTextField jtxtclassvan;
    private javax.swing.JTextField jtxtmeal;
    private javax.swing.JTextField jtxtvanMilkShake;
    // End of variables declaration//GEN-END:variables
}
